// Copyright 2025 The Go MCP SDK Authors. All rights reserved.
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.

// Code generated by internal/schemagen. DO NOT EDIT.

package acp

import (
	"context"

	"github.com/spachava753/acp-sdk/internal/jsonrpc2"
	"github.com/spachava753/acp-sdk/jsonrpc"
)

const (
	// MethodAuthenticate: Authenticates the client using the specified authentication method.
	//
	// Called when the agent requires authentication before allowing session creation.
	// The client provides the authentication method ID that was advertised during initialization.
	//
	// After successful authentication, the client can proceed to create sessions with
	// `new_session` without receiving an `auth_required` error.
	//
	// See protocol docs: [Initialization](https://agentclientprotocol.com/protocol/initialization)
	MethodAuthenticate = "authenticate"
	// MethodDocumentDidChange: **UNSTABLE**
	//
	// Notification sent when a file is edited.
	MethodDocumentDidChange = "document/didChange"
	// MethodDocumentDidClose: **UNSTABLE**
	//
	// Notification sent when a file is closed.
	MethodDocumentDidClose = "document/didClose"
	// MethodDocumentDidFocus: **UNSTABLE**
	//
	// Notification sent when a file becomes the active editor tab.
	MethodDocumentDidFocus = "document/didFocus"
	// MethodDocumentDidOpen: **UNSTABLE**
	//
	// Notification sent when a file is opened in the editor.
	MethodDocumentDidOpen = "document/didOpen"
	// MethodDocumentDidSave: **UNSTABLE**
	//
	// Notification sent when a file is saved.
	MethodDocumentDidSave = "document/didSave"
	// MethodElicitationComplete: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Notification that a URL-based elicitation has completed.
	MethodElicitationComplete = "elicitation/complete"
	// MethodElicitationCreate: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Requests structured user input via a form or URL.
	MethodElicitationCreate = "elicitation/create"
	// MethodFsReadTextFile: Reads content from a text file in the client's file system.
	//
	// Only available if the client advertises the `fs.readTextFile` capability.
	// Allows the agent to access file contents within the client's environment.
	//
	// See protocol docs: [Client](https://agentclientprotocol.com/protocol/overview#client)
	MethodFsReadTextFile = "fs/read_text_file"
	// MethodFsWriteTextFile: Writes content to a text file in the client's file system.
	//
	// Only available if the client advertises the `fs.writeTextFile` capability.
	// Allows the agent to create or modify files within the client's environment.
	//
	// See protocol docs: [Client](https://agentclientprotocol.com/protocol/overview#client)
	MethodFsWriteTextFile = "fs/write_text_file"
	// MethodInitialize: Establishes the connection with a client and negotiates protocol capabilities.
	//
	// This method is called once at the beginning of the connection to:
	// - Negotiate the protocol version to use
	// - Exchange capability information between client and agent
	// - Determine available authentication methods
	//
	// The agent should respond with its supported protocol version and capabilities.
	//
	// See protocol docs: [Initialization](https://agentclientprotocol.com/protocol/initialization)
	MethodInitialize = "initialize"
	// MethodLogout: Logs out of the current authenticated state.
	//
	// After a successful logout, all new sessions will require authentication.
	// There is no guarantee about the behavior of already running sessions.
	MethodLogout = "logout"
	// MethodMcpConnect: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Opens an MCP-over-ACP connection.
	MethodMcpConnect = "mcp/connect"
	// MethodMcpDisconnect: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Closes an MCP-over-ACP connection.
	MethodMcpDisconnect = "mcp/disconnect"
	// MethodMcpMessage: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Exchanges an MCP-over-ACP message.
	MethodMcpMessage = "mcp/message"
	// MethodNesAccept: **UNSTABLE**
	//
	// Notification sent when a suggestion is accepted.
	MethodNesAccept = "nes/accept"
	// MethodNesClose: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Closes an active NES session and frees up any resources associated with it.
	//
	// The agent must cancel any ongoing work and then free up any resources
	// associated with the NES session.
	MethodNesClose = "nes/close"
	// MethodNesReject: **UNSTABLE**
	//
	// Notification sent when a suggestion is rejected.
	MethodNesReject = "nes/reject"
	// MethodNesStart: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Starts an NES session.
	MethodNesStart = "nes/start"
	// MethodNesSuggest: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Requests a code suggestion.
	MethodNesSuggest = "nes/suggest"
	// MethodProvidersDisable: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Disables a provider.
	MethodProvidersDisable = "providers/disable"
	// MethodProvidersList: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Lists providers that can be configured by the client.
	MethodProvidersList = "providers/list"
	// MethodProvidersSet: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Replaces the configuration for a provider.
	MethodProvidersSet = "providers/set"
	// MethodSessionCancel: Cancels ongoing operations for a session.
	//
	// This is a notification sent by the client to cancel an ongoing prompt turn.
	//
	// Upon receiving this notification, the Agent SHOULD:
	// - Stop all language model requests as soon as possible
	// - Abort all tool call invocations in progress
	// - Send any pending `session/update` notifications
	// - Respond to the original `session/prompt` request with `StopReason::Cancelled`
	//
	// See protocol docs: [Cancellation](https://agentclientprotocol.com/protocol/prompt-turn#cancellation)
	MethodSessionCancel = "session/cancel"
	// MethodSessionClose: Closes an active session and frees up any resources associated with it.
	//
	// This method is only available if the agent advertises the `sessionCapabilities.close` capability.
	//
	// The agent must cancel any ongoing work (as if `session/cancel` was called)
	// and then free up any resources associated with the session.
	MethodSessionClose = "session/close"
	// MethodSessionDelete: Deletes an existing session from `session/list`.
	//
	// This method is only available if the agent advertises the `sessionCapabilities.delete` capability.
	MethodSessionDelete = "session/delete"
	// MethodSessionFork: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Forks an existing session to create a new independent session.
	//
	// This method is only available if the agent advertises the `session.fork` capability.
	//
	// The agent should create a new session with the same conversation context as the
	// original, allowing operations like generating summaries without affecting the
	// original session's history.
	MethodSessionFork = "session/fork"
	// MethodSessionList: Lists existing sessions known to the agent.
	//
	// This method is only available if the agent advertises the `sessionCapabilities.list` capability.
	//
	// The agent should return metadata about sessions with optional filtering and pagination support.
	MethodSessionList = "session/list"
	// MethodSessionLoad: Loads an existing session to resume a previous conversation.
	//
	// This method is only available if the agent advertises the `loadSession` capability.
	//
	// The agent should:
	// - Restore the session context and conversation history
	// - Connect to the specified MCP servers
	// - Stream the entire conversation history back to the client via notifications
	//
	// See protocol docs: [Loading Sessions](https://agentclientprotocol.com/protocol/session-setup#loading-sessions)
	MethodSessionLoad = "session/load"
	// MethodSessionNew: Creates a new conversation session with the agent.
	//
	// Sessions represent independent conversation contexts with their own history and state.
	//
	// The agent should:
	// - Create a new session context
	// - Connect to any specified MCP servers
	// - Return a unique session ID for future requests
	//
	// May return an `auth_required` error if the agent requires authentication.
	//
	// See protocol docs: [Session Setup](https://agentclientprotocol.com/protocol/session-setup)
	MethodSessionNew = "session/new"
	// MethodSessionPrompt: Processes a user prompt within a session.
	//
	// This method handles the whole lifecycle of a prompt:
	// - Receives user messages with optional context (files, images, etc.)
	// - Processes the prompt using language models
	// - Reports language model content and tool calls to the Clients
	// - Requests permission to run tools
	// - Executes any requested tool calls
	// - Returns when the turn is complete with a stop reason
	//
	// See protocol docs: [Prompt Turn](https://agentclientprotocol.com/protocol/prompt-turn)
	MethodSessionPrompt = "session/prompt"
	// MethodSessionRequestPermission: Requests permission from the user for a tool call operation.
	//
	// Called by the agent when it needs user authorization before executing
	// a potentially sensitive operation. The client should present the options
	// to the user and return their decision.
	//
	// If the client cancels the prompt turn via `session/cancel`, it MUST
	// respond to this request with `RequestPermissionOutcome::Cancelled`.
	//
	// See protocol docs: [Requesting Permission](https://agentclientprotocol.com/protocol/tool-calls#requesting-permission)
	MethodSessionRequestPermission = "session/request_permission"
	// MethodSessionResume: Resumes an existing session without returning previous messages.
	//
	// This method is only available if the agent advertises the `sessionCapabilities.resume` capability.
	//
	// The agent should resume the session context, allowing the conversation to continue
	// without replaying the message history (unlike `session/load`).
	MethodSessionResume = "session/resume"
	// MethodSessionSetConfigOption: Sets the current value for a session configuration option.
	MethodSessionSetConfigOption = "session/set_config_option"
	// MethodSessionSetMode: Sets the current mode for a session.
	//
	// Allows switching between different agent modes (e.g., "ask", "architect", "code")
	// that affect system prompts, tool availability, and permission behaviors.
	//
	// The mode must be one of the modes advertised in `availableModes` during session
	// creation or loading. Agents may also change modes autonomously and notify the
	// client via `current_mode_update` notifications.
	//
	// This method can be called at any time during a session, whether the Agent is
	// idle or actively generating a response.
	//
	// See protocol docs: [Session Modes](https://agentclientprotocol.com/protocol/session-modes)
	MethodSessionSetMode = "session/set_mode"
	// MethodSessionUpdate: Handles session update notifications from the agent.
	//
	// This is a notification endpoint (no response expected) that receives
	// real-time updates about session progress, including message chunks,
	// tool calls, and execution plans.
	//
	// Note: Clients SHOULD continue accepting tool call updates even after
	// sending a `session/cancel` notification, as the agent may send final
	// updates before responding with the cancelled stop reason.
	//
	// See protocol docs: [Agent Reports Output](https://agentclientprotocol.com/protocol/prompt-turn#3-agent-reports-output)
	MethodSessionUpdate = "session/update"
	// MethodTerminalCreate: Executes a command in a new terminal
	//
	// Only available if the `terminal` Client capability is set to `true`.
	//
	// Returns a `TerminalId` that can be used with other terminal methods
	// to get the current output, wait for exit, and kill the command.
	//
	// The `TerminalId` can also be used to embed the terminal in a tool call
	// by using the `ToolCallContent::Terminal` variant.
	//
	// The Agent is responsible for releasing the terminal by using the `terminal/release`
	// method.
	//
	// See protocol docs: [Terminals](https://agentclientprotocol.com/protocol/terminals)
	MethodTerminalCreate = "terminal/create"
	// MethodTerminalKill: Kills the terminal command without releasing the terminal
	//
	// While `terminal/release` will also kill the command, this method will keep
	// the `TerminalId` valid so it can be used with other methods.
	//
	// This method can be helpful when implementing command timeouts which terminate
	// the command as soon as elapsed, and then get the final output so it can be sent
	// to the model.
	//
	// Note: Call `terminal/release` when `TerminalId` is no longer needed.
	//
	// See protocol docs: [Terminals](https://agentclientprotocol.com/protocol/terminals)
	MethodTerminalKill = "terminal/kill"
	// MethodTerminalOutput: Gets the terminal output and exit status
	//
	// Returns the current content in the terminal without waiting for the command to exit.
	// If the command has already exited, the exit status is included.
	//
	// See protocol docs: [Terminals](https://agentclientprotocol.com/protocol/terminals)
	MethodTerminalOutput = "terminal/output"
	// MethodTerminalRelease: Releases a terminal
	//
	// The command is killed if it hasn't exited yet. Use `terminal/wait_for_exit`
	// to wait for the command to exit before releasing the terminal.
	//
	// After release, the `TerminalId` can no longer be used with other `terminal/*` methods,
	// but tool calls that already contain it, continue to display its output.
	//
	// The `terminal/kill` method can be used to terminate the command without releasing
	// the terminal, allowing the Agent to call `terminal/output` and other methods.
	//
	// See protocol docs: [Terminals](https://agentclientprotocol.com/protocol/terminals)
	MethodTerminalRelease = "terminal/release"
	// MethodTerminalWaitForExit: Waits for the terminal command to exit and return its exit status
	//
	// See protocol docs: [Terminals](https://agentclientprotocol.com/protocol/terminals)
	MethodTerminalWaitForExit = "terminal/wait_for_exit"
)

// AuthenticateHandler handles all authenticate related agent methods.
type AuthenticateHandler interface {
	// Authenticate: Authenticates the client using the specified authentication method.
	//
	// Called when the agent requires authentication before allowing session creation.
	// The client provides the authentication method ID that was advertised during initialization.
	//
	// After successful authentication, the client can proceed to create sessions with
	// `new_session` without receiving an `auth_required` error.
	//
	// See protocol docs: [Initialization](https://agentclientprotocol.com/protocol/initialization)
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
}

// DocumentHandler handles all document related agent methods.
type DocumentHandler interface {
	// DidChange: **UNSTABLE**
	//
	// Notification sent when a file is edited.
	DidChange(context.Context, *DidChangeDocumentNotification) error

	// DidClose: **UNSTABLE**
	//
	// Notification sent when a file is closed.
	DidClose(context.Context, *DidCloseDocumentNotification) error

	// DidFocus: **UNSTABLE**
	//
	// Notification sent when a file becomes the active editor tab.
	DidFocus(context.Context, *DidFocusDocumentNotification) error

	// DidOpen: **UNSTABLE**
	//
	// Notification sent when a file is opened in the editor.
	DidOpen(context.Context, *DidOpenDocumentNotification) error

	// DidSave: **UNSTABLE**
	//
	// Notification sent when a file is saved.
	DidSave(context.Context, *DidSaveDocumentNotification) error
}

// InitializeHandler handles all initialize related agent methods.
type InitializeHandler interface {
	// Initialize: Establishes the connection with a client and negotiates protocol capabilities.
	//
	// This method is called once at the beginning of the connection to:
	// - Negotiate the protocol version to use
	// - Exchange capability information between client and agent
	// - Determine available authentication methods
	//
	// The agent should respond with its supported protocol version and capabilities.
	//
	// See protocol docs: [Initialization](https://agentclientprotocol.com/protocol/initialization)
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
}

// LogoutHandler handles all logout related agent methods.
type LogoutHandler interface {
	// Logout: Logs out of the current authenticated state.
	//
	// After a successful logout, all new sessions will require authentication.
	// There is no guarantee about the behavior of already running sessions.
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
}

// McpHandler handles all mcp related agent methods.
type McpHandler interface {
	// MessageMcp: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Exchanges an MCP-over-ACP message.
	MessageMcp(context.Context, *MessageMcpNotification) error
}

// NesHandler handles all nes related agent methods.
type NesHandler interface {
	// Accept: **UNSTABLE**
	//
	// Notification sent when a suggestion is accepted.
	Accept(context.Context, *AcceptNesNotification) error

	// CloseNes: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Closes an active NES session and frees up any resources associated with it.
	//
	// The agent must cancel any ongoing work and then free up any resources
	// associated with the NES session.
	CloseNes(context.Context, *CloseNesRequest) (*CloseNesResponse, error)

	// Reject: **UNSTABLE**
	//
	// Notification sent when a suggestion is rejected.
	Reject(context.Context, *RejectNesNotification) error

	// StartNes: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Starts an NES session.
	StartNes(context.Context, *StartNesRequest) (*StartNesResponse, error)

	// SuggestNes: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Requests a code suggestion.
	SuggestNes(context.Context, *SuggestNesRequest) (*SuggestNesResponse, error)
}

// ProvidersHandler handles all providers related agent methods.
type ProvidersHandler interface {
	// DisableProvider: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Disables a provider.
	DisableProvider(context.Context, *DisableProviderRequest) (*DisableProviderResponse, error)

	// ListProviders: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Lists providers that can be configured by the client.
	ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error)

	// SetProvider: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Replaces the configuration for a provider.
	SetProvider(context.Context, *SetProviderRequest) (*SetProviderResponse, error)
}

// SessionHandler handles all session related agent methods.
type SessionHandler interface {
	// Cancel: Cancels ongoing operations for a session.
	//
	// This is a notification sent by the client to cancel an ongoing prompt turn.
	//
	// Upon receiving this notification, the Agent SHOULD:
	// - Stop all language model requests as soon as possible
	// - Abort all tool call invocations in progress
	// - Send any pending `session/update` notifications
	// - Respond to the original `session/prompt` request with `StopReason::Cancelled`
	//
	// See protocol docs: [Cancellation](https://agentclientprotocol.com/protocol/prompt-turn#cancellation)
	Cancel(context.Context, *CancelNotification) error

	// CloseSession: Closes an active session and frees up any resources associated with it.
	//
	// This method is only available if the agent advertises the `sessionCapabilities.close` capability.
	//
	// The agent must cancel any ongoing work (as if `session/cancel` was called)
	// and then free up any resources associated with the session.
	CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error)

	// DeleteSession: Deletes an existing session from `session/list`.
	//
	// This method is only available if the agent advertises the `sessionCapabilities.delete` capability.
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)

	// ForkSession: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Forks an existing session to create a new independent session.
	//
	// This method is only available if the agent advertises the `session.fork` capability.
	//
	// The agent should create a new session with the same conversation context as the
	// original, allowing operations like generating summaries without affecting the
	// original session's history.
	ForkSession(context.Context, *ForkSessionRequest) (*ForkSessionResponse, error)

	// ListSessions: Lists existing sessions known to the agent.
	//
	// This method is only available if the agent advertises the `sessionCapabilities.list` capability.
	//
	// The agent should return metadata about sessions with optional filtering and pagination support.
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)

	// LoadSession: Loads an existing session to resume a previous conversation.
	//
	// This method is only available if the agent advertises the `loadSession` capability.
	//
	// The agent should:
	// - Restore the session context and conversation history
	// - Connect to the specified MCP servers
	// - Stream the entire conversation history back to the client via notifications
	//
	// See protocol docs: [Loading Sessions](https://agentclientprotocol.com/protocol/session-setup#loading-sessions)
	LoadSession(context.Context, *LoadSessionRequest) (*LoadSessionResponse, error)

	// NewSession: Creates a new conversation session with the agent.
	//
	// Sessions represent independent conversation contexts with their own history and state.
	//
	// The agent should:
	// - Create a new session context
	// - Connect to any specified MCP servers
	// - Return a unique session ID for future requests
	//
	// May return an `auth_required` error if the agent requires authentication.
	//
	// See protocol docs: [Session Setup](https://agentclientprotocol.com/protocol/session-setup)
	NewSession(context.Context, *NewSessionRequest) (*NewSessionResponse, error)

	// Prompt: Processes a user prompt within a session.
	//
	// This method handles the whole lifecycle of a prompt:
	// - Receives user messages with optional context (files, images, etc.)
	// - Processes the prompt using language models
	// - Reports language model content and tool calls to the Clients
	// - Requests permission to run tools
	// - Executes any requested tool calls
	// - Returns when the turn is complete with a stop reason
	//
	// See protocol docs: [Prompt Turn](https://agentclientprotocol.com/protocol/prompt-turn)
	Prompt(context.Context, *PromptRequest) (*PromptResponse, error)

	// ResumeSession: Resumes an existing session without returning previous messages.
	//
	// This method is only available if the agent advertises the `sessionCapabilities.resume` capability.
	//
	// The agent should resume the session context, allowing the conversation to continue
	// without replaying the message history (unlike `session/load`).
	ResumeSession(context.Context, *ResumeSessionRequest) (*ResumeSessionResponse, error)

	// SetSessionConfigOption: Sets the current value for a session configuration option.
	SetSessionConfigOption(context.Context, *SetSessionConfigOptionRequest) (*SetSessionConfigOptionResponse, error)

	// SetSessionMode: Sets the current mode for a session.
	//
	// Allows switching between different agent modes (e.g., "ask", "architect", "code")
	// that affect system prompts, tool availability, and permission behaviors.
	//
	// The mode must be one of the modes advertised in `availableModes` during session
	// creation or loading. Agents may also change modes autonomously and notify the
	// client via `current_mode_update` notifications.
	//
	// This method can be called at any time during a session, whether the Agent is
	// idle or actively generating a response.
	//
	// See protocol docs: [Session Modes](https://agentclientprotocol.com/protocol/session-modes)
	SetSessionMode(context.Context, *SetSessionModeRequest) (*SetSessionModeResponse, error)
}

// Complete: **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Notification that a URL-based elicitation has completed.
func (c *AgentConnection) Complete(ctx context.Context, params *CompleteElicitationNotification) error {
	return notify(ctx, c.rpc.conn, MethodElicitationComplete, params)
}

// CreateElicitation: **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Requests structured user input via a form or URL.
func (c *AgentConnection) CreateElicitation(ctx context.Context, params *CreateElicitationRequest) (*CreateElicitationResponse, error) {
	return call[CreateElicitationResponse](ctx, c.rpc.conn, MethodElicitationCreate, params)
}

// ReadTextFile: Reads content from a text file in the client's file system.
//
// Only available if the client advertises the `fs.readTextFile` capability.
// Allows the agent to access file contents within the client's environment.
//
// See protocol docs: [Client](https://agentclientprotocol.com/protocol/overview#client)
func (c *AgentConnection) ReadTextFile(ctx context.Context, params *ReadTextFileRequest) (*ReadTextFileResponse, error) {
	return call[ReadTextFileResponse](ctx, c.rpc.conn, MethodFsReadTextFile, params)
}

// WriteTextFile: Writes content to a text file in the client's file system.
//
// Only available if the client advertises the `fs.writeTextFile` capability.
// Allows the agent to create or modify files within the client's environment.
//
// See protocol docs: [Client](https://agentclientprotocol.com/protocol/overview#client)
func (c *AgentConnection) WriteTextFile(ctx context.Context, params *WriteTextFileRequest) (*WriteTextFileResponse, error) {
	return call[WriteTextFileResponse](ctx, c.rpc.conn, MethodFsWriteTextFile, params)
}

// ConnectMcp: **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Opens an MCP-over-ACP connection.
func (c *AgentConnection) ConnectMcp(ctx context.Context, params *ConnectMcpRequest) (*ConnectMcpResponse, error) {
	return call[ConnectMcpResponse](ctx, c.rpc.conn, MethodMcpConnect, params)
}

// DisconnectMcp: **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Closes an MCP-over-ACP connection.
func (c *AgentConnection) DisconnectMcp(ctx context.Context, params *DisconnectMcpRequest) (*DisconnectMcpResponse, error) {
	return call[DisconnectMcpResponse](ctx, c.rpc.conn, MethodMcpDisconnect, params)
}

// MessageMcp: **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Exchanges an MCP-over-ACP message.
func (c *AgentConnection) MessageMcp(ctx context.Context, params *MessageMcpNotification) error {
	return notify(ctx, c.rpc.conn, MethodMcpMessage, params)
}

// RequestPermission: Requests permission from the user for a tool call operation.
//
// Called by the agent when it needs user authorization before executing
// a potentially sensitive operation. The client should present the options
// to the user and return their decision.
//
// If the client cancels the prompt turn via `session/cancel`, it MUST
// respond to this request with `RequestPermissionOutcome::Cancelled`.
//
// See protocol docs: [Requesting Permission](https://agentclientprotocol.com/protocol/tool-calls#requesting-permission)
func (c *AgentConnection) RequestPermission(ctx context.Context, params *RequestPermissionRequest) (*RequestPermissionResponse, error) {
	return call[RequestPermissionResponse](ctx, c.rpc.conn, MethodSessionRequestPermission, params)
}

// Update: Handles session update notifications from the agent.
//
// This is a notification endpoint (no response expected) that receives
// real-time updates about session progress, including message chunks,
// tool calls, and execution plans.
//
// Note: Clients SHOULD continue accepting tool call updates even after
// sending a `session/cancel` notification, as the agent may send final
// updates before responding with the cancelled stop reason.
//
// See protocol docs: [Agent Reports Output](https://agentclientprotocol.com/protocol/prompt-turn#3-agent-reports-output)
func (c *AgentConnection) Update(ctx context.Context, params *SessionNotification) error {
	return notify(ctx, c.rpc.conn, MethodSessionUpdate, params)
}

// CreateTerminal: Executes a command in a new terminal
//
// Only available if the `terminal` Client capability is set to `true`.
//
// Returns a `TerminalId` that can be used with other terminal methods
// to get the current output, wait for exit, and kill the command.
//
// The `TerminalId` can also be used to embed the terminal in a tool call
// by using the `ToolCallContent::Terminal` variant.
//
// The Agent is responsible for releasing the terminal by using the `terminal/release`
// method.
//
// See protocol docs: [Terminals](https://agentclientprotocol.com/protocol/terminals)
func (c *AgentConnection) CreateTerminal(ctx context.Context, params *CreateTerminalRequest) (*CreateTerminalResponse, error) {
	return call[CreateTerminalResponse](ctx, c.rpc.conn, MethodTerminalCreate, params)
}

// KillTerminal: Kills the terminal command without releasing the terminal
//
// While `terminal/release` will also kill the command, this method will keep
// the `TerminalId` valid so it can be used with other methods.
//
// This method can be helpful when implementing command timeouts which terminate
// the command as soon as elapsed, and then get the final output so it can be sent
// to the model.
//
// Note: Call `terminal/release` when `TerminalId` is no longer needed.
//
// See protocol docs: [Terminals](https://agentclientprotocol.com/protocol/terminals)
func (c *AgentConnection) KillTerminal(ctx context.Context, params *KillTerminalRequest) (*KillTerminalResponse, error) {
	return call[KillTerminalResponse](ctx, c.rpc.conn, MethodTerminalKill, params)
}

// TerminalOutput: Gets the terminal output and exit status
//
// Returns the current content in the terminal without waiting for the command to exit.
// If the command has already exited, the exit status is included.
//
// See protocol docs: [Terminals](https://agentclientprotocol.com/protocol/terminals)
func (c *AgentConnection) TerminalOutput(ctx context.Context, params *TerminalOutputRequest) (*TerminalOutputResponse, error) {
	return call[TerminalOutputResponse](ctx, c.rpc.conn, MethodTerminalOutput, params)
}

// ReleaseTerminal: Releases a terminal
//
// The command is killed if it hasn't exited yet. Use `terminal/wait_for_exit`
// to wait for the command to exit before releasing the terminal.
//
// After release, the `TerminalId` can no longer be used with other `terminal/*` methods,
// but tool calls that already contain it, continue to display its output.
//
// The `terminal/kill` method can be used to terminate the command without releasing
// the terminal, allowing the Agent to call `terminal/output` and other methods.
//
// See protocol docs: [Terminals](https://agentclientprotocol.com/protocol/terminals)
func (c *AgentConnection) ReleaseTerminal(ctx context.Context, params *ReleaseTerminalRequest) (*ReleaseTerminalResponse, error) {
	return call[ReleaseTerminalResponse](ctx, c.rpc.conn, MethodTerminalRelease, params)
}

// WaitForTerminalExit: Waits for the terminal command to exit and return its exit status
//
// See protocol docs: [Terminals](https://agentclientprotocol.com/protocol/terminals)
func (c *AgentConnection) WaitForTerminalExit(ctx context.Context, params *WaitForTerminalExitRequest) (*WaitForTerminalExitResponse, error) {
	return call[WaitForTerminalExitResponse](ctx, c.rpc.conn, MethodTerminalWaitForExit, params)
}

func handleAgentRequest(ctx context.Context, agent any, req *jsonrpc.Request) (any, error) {
	jsonrpc2.Async(ctx)
	if agent == nil {
		return nil, methodNotFound(req.Method)
	}
	switch req.Method {
	case MethodAuthenticate:
		handler, ok := agent.(AuthenticateHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[AuthenticateRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.Authenticate(ctx, params))
	case MethodDocumentDidChange:
		handler, ok := agent.(DocumentHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[DidChangeDocumentNotification](req)
		if err != nil {
			return nil, err
		}
		return nil, handler.DidChange(ctx, params)
	case MethodDocumentDidClose:
		handler, ok := agent.(DocumentHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[DidCloseDocumentNotification](req)
		if err != nil {
			return nil, err
		}
		return nil, handler.DidClose(ctx, params)
	case MethodDocumentDidFocus:
		handler, ok := agent.(DocumentHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[DidFocusDocumentNotification](req)
		if err != nil {
			return nil, err
		}
		return nil, handler.DidFocus(ctx, params)
	case MethodDocumentDidOpen:
		handler, ok := agent.(DocumentHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[DidOpenDocumentNotification](req)
		if err != nil {
			return nil, err
		}
		return nil, handler.DidOpen(ctx, params)
	case MethodDocumentDidSave:
		handler, ok := agent.(DocumentHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[DidSaveDocumentNotification](req)
		if err != nil {
			return nil, err
		}
		return nil, handler.DidSave(ctx, params)
	case MethodInitialize:
		handler, ok := agent.(InitializeHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[InitializeRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.Initialize(ctx, params))
	case MethodLogout:
		handler, ok := agent.(LogoutHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[LogoutRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.Logout(ctx, params))
	case MethodMcpMessage:
		handler, ok := agent.(McpHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[MessageMcpNotification](req)
		if err != nil {
			return nil, err
		}
		return nil, handler.MessageMcp(ctx, params)
	case MethodNesAccept:
		handler, ok := agent.(NesHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[AcceptNesNotification](req)
		if err != nil {
			return nil, err
		}
		return nil, handler.Accept(ctx, params)
	case MethodNesClose:
		handler, ok := agent.(NesHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[CloseNesRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.CloseNes(ctx, params))
	case MethodNesReject:
		handler, ok := agent.(NesHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[RejectNesNotification](req)
		if err != nil {
			return nil, err
		}
		return nil, handler.Reject(ctx, params)
	case MethodNesStart:
		handler, ok := agent.(NesHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[StartNesRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.StartNes(ctx, params))
	case MethodNesSuggest:
		handler, ok := agent.(NesHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[SuggestNesRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.SuggestNes(ctx, params))
	case MethodProvidersDisable:
		handler, ok := agent.(ProvidersHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[DisableProviderRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.DisableProvider(ctx, params))
	case MethodProvidersList:
		handler, ok := agent.(ProvidersHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[ListProvidersRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.ListProviders(ctx, params))
	case MethodProvidersSet:
		handler, ok := agent.(ProvidersHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[SetProviderRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.SetProvider(ctx, params))
	case MethodSessionCancel:
		handler, ok := agent.(SessionHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[CancelNotification](req)
		if err != nil {
			return nil, err
		}
		return nil, handler.Cancel(ctx, params)
	case MethodSessionClose:
		handler, ok := agent.(SessionHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[CloseSessionRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.CloseSession(ctx, params))
	case MethodSessionDelete:
		handler, ok := agent.(SessionHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[DeleteSessionRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.DeleteSession(ctx, params))
	case MethodSessionFork:
		handler, ok := agent.(SessionHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[ForkSessionRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.ForkSession(ctx, params))
	case MethodSessionList:
		handler, ok := agent.(SessionHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[ListSessionsRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.ListSessions(ctx, params))
	case MethodSessionLoad:
		handler, ok := agent.(SessionHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[LoadSessionRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.LoadSession(ctx, params))
	case MethodSessionNew:
		handler, ok := agent.(SessionHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[NewSessionRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.NewSession(ctx, params))
	case MethodSessionPrompt:
		handler, ok := agent.(SessionHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[PromptRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.Prompt(ctx, params))
	case MethodSessionResume:
		handler, ok := agent.(SessionHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[ResumeSessionRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.ResumeSession(ctx, params))
	case MethodSessionSetConfigOption:
		handler, ok := agent.(SessionHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[SetSessionConfigOptionRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.SetSessionConfigOption(ctx, params))
	case MethodSessionSetMode:
		handler, ok := agent.(SessionHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[SetSessionModeRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.SetSessionMode(ctx, params))
	default:
		return nil, methodNotFound(req.Method)
	}
}
