// Copyright 2025 The Go MCP SDK Authors. All rights reserved.
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.

// Code generated by internal/schemagen. DO NOT EDIT.

package acp

import (
	"context"

	"github.com/spachava753/acp-sdk/internal/jsonrpc2"
	"github.com/spachava753/acp-sdk/jsonrpc"
)

// ElicitationClientHandler handles all elicitation related client methods.
type ElicitationClientHandler interface {
	// Complete: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Notification that a URL-based elicitation has completed.
	Complete(context.Context, *CompleteElicitationNotification) error

	// CreateElicitation: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Requests structured user input via a form or URL.
	CreateElicitation(context.Context, *CreateElicitationRequest) (*CreateElicitationResponse, error)
}

// FsClientHandler handles all fs related client methods.
type FsClientHandler interface {
	// ReadTextFile: Reads content from a text file in the client's file system.
	//
	// Only available if the client advertises the `fs.readTextFile` capability.
	// Allows the agent to access file contents within the client's environment.
	//
	// See protocol docs: [Client](https://agentclientprotocol.com/protocol/overview#client)
	ReadTextFile(context.Context, *ReadTextFileRequest) (*ReadTextFileResponse, error)

	// WriteTextFile: Writes content to a text file in the client's file system.
	//
	// Only available if the client advertises the `fs.writeTextFile` capability.
	// Allows the agent to create or modify files within the client's environment.
	//
	// See protocol docs: [Client](https://agentclientprotocol.com/protocol/overview#client)
	WriteTextFile(context.Context, *WriteTextFileRequest) (*WriteTextFileResponse, error)
}

// McpClientHandler handles all mcp related client methods.
type McpClientHandler interface {
	// ConnectMcp: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Opens an MCP-over-ACP connection.
	ConnectMcp(context.Context, *ConnectMcpRequest) (*ConnectMcpResponse, error)

	// DisconnectMcp: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Closes an MCP-over-ACP connection.
	DisconnectMcp(context.Context, *DisconnectMcpRequest) (*DisconnectMcpResponse, error)

	// Message: **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Receives an MCP-over-ACP notification.
	Message(context.Context, *MessageMcpNotification) error
}

// SessionClientHandler handles all session related client methods.
type SessionClientHandler interface {
	// RequestPermission: Requests permission from the user for a tool call operation.
	//
	// Called by the agent when it needs user authorization before executing
	// a potentially sensitive operation. The client should present the options
	// to the user and return their decision.
	//
	// If the client cancels the prompt turn via `session/cancel`, it MUST
	// respond to this request with `RequestPermissionOutcome::Cancelled`.
	//
	// See protocol docs: [Requesting Permission](https://agentclientprotocol.com/protocol/tool-calls#requesting-permission)
	RequestPermission(context.Context, *RequestPermissionRequest) (*RequestPermissionResponse, error)

	// Update: Handles session update notifications from the agent.
	//
	// This is a notification endpoint (no response expected) that receives
	// real-time updates about session progress, including message chunks,
	// tool calls, and execution plans.
	//
	// Note: Clients SHOULD continue accepting tool call updates even after
	// sending a `session/cancel` notification, as the agent may send final
	// updates before responding with the cancelled stop reason.
	//
	// See protocol docs: [Agent Reports Output](https://agentclientprotocol.com/protocol/prompt-turn#3-agent-reports-output)
	Update(context.Context, *SessionNotification) error
}

// TerminalClientHandler handles all terminal related client methods.
type TerminalClientHandler interface {
	// CreateTerminal: Executes a command in a new terminal
	//
	// Only available if the `terminal` Client capability is set to `true`.
	//
	// Returns a `TerminalId` that can be used with other terminal methods
	// to get the current output, wait for exit, and kill the command.
	//
	// The `TerminalId` can also be used to embed the terminal in a tool call
	// by using the `ToolCallContent::Terminal` variant.
	//
	// The Agent is responsible for releasing the terminal by using the `terminal/release`
	// method.
	//
	// See protocol docs: [Terminals](https://agentclientprotocol.com/protocol/terminals)
	CreateTerminal(context.Context, *CreateTerminalRequest) (*CreateTerminalResponse, error)

	// KillTerminal: Kills the terminal command without releasing the terminal
	//
	// While `terminal/release` will also kill the command, this method will keep
	// the `TerminalId` valid so it can be used with other methods.
	//
	// This method can be helpful when implementing command timeouts which terminate
	// the command as soon as elapsed, and then get the final output so it can be sent
	// to the model.
	//
	// Note: Call `terminal/release` when `TerminalId` is no longer needed.
	//
	// See protocol docs: [Terminals](https://agentclientprotocol.com/protocol/terminals)
	KillTerminal(context.Context, *KillTerminalRequest) (*KillTerminalResponse, error)

	// TerminalOutput: Gets the terminal output and exit status
	//
	// Returns the current content in the terminal without waiting for the command to exit.
	// If the command has already exited, the exit status is included.
	//
	// See protocol docs: [Terminals](https://agentclientprotocol.com/protocol/terminals)
	TerminalOutput(context.Context, *TerminalOutputRequest) (*TerminalOutputResponse, error)

	// ReleaseTerminal: Releases a terminal
	//
	// The command is killed if it hasn't exited yet. Use `terminal/wait_for_exit`
	// to wait for the command to exit before releasing the terminal.
	//
	// After release, the `TerminalId` can no longer be used with other `terminal/*` methods,
	// but tool calls that already contain it, continue to display its output.
	//
	// The `terminal/kill` method can be used to terminate the command without releasing
	// the terminal, allowing the Agent to call `terminal/output` and other methods.
	//
	// See protocol docs: [Terminals](https://agentclientprotocol.com/protocol/terminals)
	ReleaseTerminal(context.Context, *ReleaseTerminalRequest) (*ReleaseTerminalResponse, error)

	// WaitForTerminalExit: Waits for the terminal command to exit and return its exit status
	//
	// See protocol docs: [Terminals](https://agentclientprotocol.com/protocol/terminals)
	WaitForTerminalExit(context.Context, *WaitForTerminalExitRequest) (*WaitForTerminalExitResponse, error)
}

// Authenticate: Authenticates the client using the specified authentication method.
//
// Called when the agent requires authentication before allowing session creation.
// The client provides the authentication method ID that was advertised during initialization.
//
// After successful authentication, the client can proceed to create sessions with
// `new_session` without receiving an `auth_required` error.
//
// See protocol docs: [Initialization](https://agentclientprotocol.com/protocol/initialization)
func (c *Client) Authenticate(ctx context.Context, params *AuthenticateRequest) (*AuthenticateResponse, error) {
	return call[AuthenticateResponse](ctx, c.rpc.conn, MethodAuthenticate, params)
}

// DidChange: **UNSTABLE**
//
// Notification sent when a file is edited.
func (c *Client) DidChange(ctx context.Context, params *DidChangeDocumentNotification) error {
	return notify(ctx, c.rpc.conn, MethodDocumentDidChange, params)
}

// DidClose: **UNSTABLE**
//
// Notification sent when a file is closed.
func (c *Client) DidClose(ctx context.Context, params *DidCloseDocumentNotification) error {
	return notify(ctx, c.rpc.conn, MethodDocumentDidClose, params)
}

// DidFocus: **UNSTABLE**
//
// Notification sent when a file becomes the active editor tab.
func (c *Client) DidFocus(ctx context.Context, params *DidFocusDocumentNotification) error {
	return notify(ctx, c.rpc.conn, MethodDocumentDidFocus, params)
}

// DidOpen: **UNSTABLE**
//
// Notification sent when a file is opened in the editor.
func (c *Client) DidOpen(ctx context.Context, params *DidOpenDocumentNotification) error {
	return notify(ctx, c.rpc.conn, MethodDocumentDidOpen, params)
}

// DidSave: **UNSTABLE**
//
// Notification sent when a file is saved.
func (c *Client) DidSave(ctx context.Context, params *DidSaveDocumentNotification) error {
	return notify(ctx, c.rpc.conn, MethodDocumentDidSave, params)
}

// Initialize: Establishes the connection with a client and negotiates protocol capabilities.
//
// This method is called once at the beginning of the connection to:
// - Negotiate the protocol version to use
// - Exchange capability information between client and agent
// - Determine available authentication methods
//
// The agent should respond with its supported protocol version and capabilities.
//
// See protocol docs: [Initialization](https://agentclientprotocol.com/protocol/initialization)
func (c *Client) Initialize(ctx context.Context, params *InitializeRequest) (*InitializeResponse, error) {
	return call[InitializeResponse](ctx, c.rpc.conn, MethodInitialize, params)
}

// Logout: Logs out of the current authenticated state.
//
// After a successful logout, all new sessions will require authentication.
// There is no guarantee about the behavior of already running sessions.
func (c *Client) Logout(ctx context.Context, params *LogoutRequest) (*LogoutResponse, error) {
	return call[LogoutResponse](ctx, c.rpc.conn, MethodLogout, params)
}

// Message: **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Receives an MCP-over-ACP notification.
func (c *Client) Message(ctx context.Context, params *MessageMcpNotification) error {
	return notify(ctx, c.rpc.conn, MethodMcpMessage, params)
}

// Accept: **UNSTABLE**
//
// Notification sent when a suggestion is accepted.
func (c *Client) Accept(ctx context.Context, params *AcceptNesNotification) error {
	return notify(ctx, c.rpc.conn, MethodNesAccept, params)
}

// CloseNes: **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Closes an active NES session and frees up any resources associated with it.
//
// The agent must cancel any ongoing work and then free up any resources
// associated with the NES session.
func (c *Client) CloseNes(ctx context.Context, params *CloseNesRequest) (*CloseNesResponse, error) {
	return call[CloseNesResponse](ctx, c.rpc.conn, MethodNesClose, params)
}

// Reject: **UNSTABLE**
//
// Notification sent when a suggestion is rejected.
func (c *Client) Reject(ctx context.Context, params *RejectNesNotification) error {
	return notify(ctx, c.rpc.conn, MethodNesReject, params)
}

// StartNes: **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Starts an NES session.
func (c *Client) StartNes(ctx context.Context, params *StartNesRequest) (*StartNesResponse, error) {
	return call[StartNesResponse](ctx, c.rpc.conn, MethodNesStart, params)
}

// SuggestNes: **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Requests a code suggestion.
func (c *Client) SuggestNes(ctx context.Context, params *SuggestNesRequest) (*SuggestNesResponse, error) {
	return call[SuggestNesResponse](ctx, c.rpc.conn, MethodNesSuggest, params)
}

// DisableProvider: **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Disables a provider.
func (c *Client) DisableProvider(ctx context.Context, params *DisableProviderRequest) (*DisableProviderResponse, error) {
	return call[DisableProviderResponse](ctx, c.rpc.conn, MethodProvidersDisable, params)
}

// ListProviders: **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Lists providers that can be configured by the client.
func (c *Client) ListProviders(ctx context.Context, params *ListProvidersRequest) (*ListProvidersResponse, error) {
	return call[ListProvidersResponse](ctx, c.rpc.conn, MethodProvidersList, params)
}

// SetProvider: **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Replaces the configuration for a provider.
func (c *Client) SetProvider(ctx context.Context, params *SetProviderRequest) (*SetProviderResponse, error) {
	return call[SetProviderResponse](ctx, c.rpc.conn, MethodProvidersSet, params)
}

// Cancel: Cancels ongoing operations for a session.
//
// This is a notification sent by the client to cancel an ongoing prompt turn.
//
// Upon receiving this notification, the Agent SHOULD:
// - Stop all language model requests as soon as possible
// - Abort all tool call invocations in progress
// - Send any pending `session/update` notifications
// - Respond to the original `session/prompt` request with `StopReason::Cancelled`
//
// See protocol docs: [Cancellation](https://agentclientprotocol.com/protocol/prompt-turn#cancellation)
func (c *Client) Cancel(ctx context.Context, params *CancelNotification) error {
	return notify(ctx, c.rpc.conn, MethodSessionCancel, params)
}

// CloseSession: Closes an active session and frees up any resources associated with it.
//
// This method is only available if the agent advertises the `sessionCapabilities.close` capability.
//
// The agent must cancel any ongoing work (as if `session/cancel` was called)
// and then free up any resources associated with the session.
func (c *Client) CloseSession(ctx context.Context, params *CloseSessionRequest) (*CloseSessionResponse, error) {
	return call[CloseSessionResponse](ctx, c.rpc.conn, MethodSessionClose, params)
}

// DeleteSession: Deletes an existing session from `session/list`.
//
// This method is only available if the agent advertises the `sessionCapabilities.delete` capability.
func (c *Client) DeleteSession(ctx context.Context, params *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return call[DeleteSessionResponse](ctx, c.rpc.conn, MethodSessionDelete, params)
}

// ForkSession: **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Forks an existing session to create a new independent session.
//
// This method is only available if the agent advertises the `session.fork` capability.
//
// The agent should create a new session with the same conversation context as the
// original, allowing operations like generating summaries without affecting the
// original session's history.
func (c *Client) ForkSession(ctx context.Context, params *ForkSessionRequest) (*ForkSessionResponse, error) {
	return call[ForkSessionResponse](ctx, c.rpc.conn, MethodSessionFork, params)
}

// ListSessions: Lists existing sessions known to the agent.
//
// This method is only available if the agent advertises the `sessionCapabilities.list` capability.
//
// The agent should return metadata about sessions with optional filtering and pagination support.
func (c *Client) ListSessions(ctx context.Context, params *ListSessionsRequest) (*ListSessionsResponse, error) {
	return call[ListSessionsResponse](ctx, c.rpc.conn, MethodSessionList, params)
}

// LoadSession: Loads an existing session to resume a previous conversation.
//
// This method is only available if the agent advertises the `loadSession` capability.
//
// The agent should:
// - Restore the session context and conversation history
// - Connect to the specified MCP servers
// - Stream the entire conversation history back to the client via notifications
//
// See protocol docs: [Loading Sessions](https://agentclientprotocol.com/protocol/session-setup#loading-sessions)
func (c *Client) LoadSession(ctx context.Context, params *LoadSessionRequest) (*LoadSessionResponse, error) {
	return call[LoadSessionResponse](ctx, c.rpc.conn, MethodSessionLoad, params)
}

// NewSession: Creates a new conversation session with the agent.
//
// Sessions represent independent conversation contexts with their own history and state.
//
// The agent should:
// - Create a new session context
// - Connect to any specified MCP servers
// - Return a unique session ID for future requests
//
// May return an `auth_required` error if the agent requires authentication.
//
// See protocol docs: [Session Setup](https://agentclientprotocol.com/protocol/session-setup)
func (c *Client) NewSession(ctx context.Context, params *NewSessionRequest) (*NewSessionResponse, error) {
	return call[NewSessionResponse](ctx, c.rpc.conn, MethodSessionNew, params)
}

// Prompt: Processes a user prompt within a session.
//
// This method handles the whole lifecycle of a prompt:
// - Receives user messages with optional context (files, images, etc.)
// - Processes the prompt using language models
// - Reports language model content and tool calls to the Clients
// - Requests permission to run tools
// - Executes any requested tool calls
// - Returns when the turn is complete with a stop reason
//
// See protocol docs: [Prompt Turn](https://agentclientprotocol.com/protocol/prompt-turn)
func (c *Client) Prompt(ctx context.Context, params *PromptRequest) (*PromptResponse, error) {
	return call[PromptResponse](ctx, c.rpc.conn, MethodSessionPrompt, params)
}

// ResumeSession: Resumes an existing session without returning previous messages.
//
// This method is only available if the agent advertises the `sessionCapabilities.resume` capability.
//
// The agent should resume the session context, allowing the conversation to continue
// without replaying the message history (unlike `session/load`).
func (c *Client) ResumeSession(ctx context.Context, params *ResumeSessionRequest) (*ResumeSessionResponse, error) {
	return call[ResumeSessionResponse](ctx, c.rpc.conn, MethodSessionResume, params)
}

// SetSessionConfigOption: Sets the current value for a session configuration option.
func (c *Client) SetSessionConfigOption(ctx context.Context, params *SetSessionConfigOptionRequest) (*SetSessionConfigOptionResponse, error) {
	return call[SetSessionConfigOptionResponse](ctx, c.rpc.conn, MethodSessionSetConfigOption, params)
}

// SetSessionMode: Sets the current mode for a session.
//
// Allows switching between different agent modes (e.g., "ask", "architect", "code")
// that affect system prompts, tool availability, and permission behaviors.
//
// The mode must be one of the modes advertised in `availableModes` during session
// creation or loading. Agents may also change modes autonomously and notify the
// client via `current_mode_update` notifications.
//
// This method can be called at any time during a session, whether the Agent is
// idle or actively generating a response.
//
// See protocol docs: [Session Modes](https://agentclientprotocol.com/protocol/session-modes)
func (c *Client) SetSessionMode(ctx context.Context, params *SetSessionModeRequest) (*SetSessionModeResponse, error) {
	return call[SetSessionModeResponse](ctx, c.rpc.conn, MethodSessionSetMode, params)
}

func (c *Client) handle(ctx context.Context, req *jsonrpc.Request) (any, error) {
	jsonrpc2.Async(ctx)
	if c.handler == nil {
		return nil, methodNotFound(req.Method)
	}
	switch req.Method {
	case MethodElicitationComplete:
		handler, ok := c.handler.(ElicitationClientHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[CompleteElicitationNotification](req)
		if err != nil {
			return nil, err
		}
		return nil, handler.Complete(ctx, params)
	case MethodElicitationCreate:
		handler, ok := c.handler.(ElicitationClientHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[CreateElicitationRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.CreateElicitation(ctx, params))
	case MethodFsReadTextFile:
		handler, ok := c.handler.(FsClientHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[ReadTextFileRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.ReadTextFile(ctx, params))
	case MethodFsWriteTextFile:
		handler, ok := c.handler.(FsClientHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[WriteTextFileRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.WriteTextFile(ctx, params))
	case MethodMcpConnect:
		handler, ok := c.handler.(McpClientHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[ConnectMcpRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.ConnectMcp(ctx, params))
	case MethodMcpDisconnect:
		handler, ok := c.handler.(McpClientHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[DisconnectMcpRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.DisconnectMcp(ctx, params))
	case MethodMcpMessage:
		handler, ok := c.handler.(McpClientHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[MessageMcpNotification](req)
		if err != nil {
			return nil, err
		}
		return nil, handler.Message(ctx, params)
	case MethodSessionRequestPermission:
		handler, ok := c.handler.(SessionClientHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[RequestPermissionRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.RequestPermission(ctx, params))
	case MethodSessionUpdate:
		handler, ok := c.handler.(SessionClientHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[SessionNotification](req)
		if err != nil {
			return nil, err
		}
		return nil, handler.Update(ctx, params)
	case MethodTerminalCreate:
		handler, ok := c.handler.(TerminalClientHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[CreateTerminalRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.CreateTerminal(ctx, params))
	case MethodTerminalKill:
		handler, ok := c.handler.(TerminalClientHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[KillTerminalRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.KillTerminal(ctx, params))
	case MethodTerminalOutput:
		handler, ok := c.handler.(TerminalClientHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[TerminalOutputRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.TerminalOutput(ctx, params))
	case MethodTerminalRelease:
		handler, ok := c.handler.(TerminalClientHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[ReleaseTerminalRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.ReleaseTerminal(ctx, params))
	case MethodTerminalWaitForExit:
		handler, ok := c.handler.(TerminalClientHandler)
		if !ok {
			return nil, methodNotFound(req.Method)
		}
		params, err := decodeParams[WaitForTerminalExitRequest](req)
		if err != nil {
			return nil, err
		}
		return rpcResult(handler.WaitForTerminalExit(ctx, params))
	default:
		return nil, methodNotFound(req.Method)
	}
}
