// Copyright 2025 The Go MCP SDK Authors. All rights reserved.
// Use of this source code is governed by the license
// that can be found in the LICENSE file.

// Command acpgen regenerates the checked-in ACP files from the protocol schema.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/google/jsonschema-go/jsonschema"
	"github.com/spachava753/acp-sdk/internal/schemagen"
)

const generatedHeader = `// Copyright 2025 The Go MCP SDK Authors. All rights reserved.
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.

// Code generated by internal/schemagen. DO NOT EDIT.

`

func main() {
	schemaPath := flag.String("schema", filepath.FromSlash("internal/schemagen/schema.json"), "path to the ACP JSON schema")
	outDir := flag.String("out", "acp", "directory for generated Go files")
	flag.Parse()

	if err := run(*schemaPath, *outDir); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(schemaPath, outDir string) error {
	data, err := os.ReadFile(schemaPath)
	if err != nil {
		return err
	}
	var schema jsonschema.Schema
	if err := json.Unmarshal(data, &schema); err != nil {
		return err
	}
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}
	files := schemagen.Generate(&schema)
	if len(files) == 0 {
		return fmt.Errorf("schemagen produced no files for %s", schemaPath)
	}
	for _, file := range files {
		contents := addGeneratedFileScaffolding(file.Filename, file.Contents)
		if err := os.WriteFile(filepath.Join(outDir, file.Filename), contents, 0644); err != nil {
			return err
		}
	}
	return nil
}

func addGeneratedFileScaffolding(filename string, contents []byte) []byte {
	if filename == "agent_gen.go" || filename == "client_gen.go" {
		contents = addRPCImports(contents)
	}
	return append([]byte(generatedHeader), contents...)
}

func addRPCImports(contents []byte) []byte {
	const pkg = "package acp\n\n"
	const imports = `package acp

import (
	"context"

	"github.com/spachava753/acp-sdk/internal/jsonrpc2"
	"github.com/spachava753/acp-sdk/jsonrpc"
)

`
	return bytes.Replace(contents, []byte(pkg), []byte(imports), 1)
}
